default_language_version:
    python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-builtin-literals
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
